### ISSUE TITLE
Java Jigsaw issue with DirectBuffer

### ISSUE THREAD

**Issue by tuxedo0801** [rrd4j/rrd4j#117] opened 2018-07-17 06:54 UTC
Hey there,

when trying to create an test graph using java10, I get

```java
Exception in thread "main" java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner;
        at org.rrd4j.core.RrdNioBackend.unmapFile(RrdNioBackend.java:73)
        at org.rrd4j.core.RrdNioBackend.close(RrdNioBackend.java:137)
        at org.rrd4j.core.RrdDb.close(RrdDb.java:504)
        at org.rrd4j.data.DataProcessor.releaseRrd(DataProcessor.java:875)
        at org.rrd4j.data.DataProcessor.fetchRrdData(DataProcessor.java:777)
        at org.rrd4j.data.DataProcessor.processData(DataProcessor.java:611)
        at org.rrd4j.graph.RrdGraph.fetchData(RrdGraph.java:611)
        at org.rrd4j.graph.RrdGraph.createGraph(RrdGraph.java:70)
        at org.rrd4j.graph.RrdGraph.<init>(RrdGraph.java:49)
```

_sun.nio.ch.DirectBuffer_ seem to be no longer part of java>=9?

**Comment by fbacchella** [comment] 2018-07-17 07:15
duplicate of #72

**Closed by fbacchella** 2018-07-17 07:15 UTC
