### ISSUE TITLE
ByteBufferBackend.get fails with BufferUnderflow

### ISSUE THREAD

**Issue by hbs** [rrd4j/rrd4j#135] opened 2019-12-26 17:14 UTC
The implementation of the get method (called when calling getBytes on an RrdDb instance) does not modify the buffer position prior to fetching bytes.

**Comment by fbacchella** [comment] 2019-12-26 17:20
Can you provide some code to generate this BufferUnderflow ?

**Comment by hbs** [comment] 2019-12-26 17:41
RrdDb rrd = RrdDb.getBuilder().setPath("imported.rrd").setExternalPath("rrdtool://path/to/file.rrd").setBackendFactory(new RrdMemoryBackendFactory()).build();
rrd.getBytes();

**Comment by hbs** [comment] 2019-12-26 19:54
The issue probably comes from the fact that the 'offset' parameter is incorrectly used in the call to ByteBuffer#get in ByteBufferBackend#read.

The 'offset' parameter should be used to set the position of the buffer and the get call should use 0 as its offset to indicate the array should be used from the beginning.

**Comment by fbacchella** [comment] 2019-12-26 20:35
It's not a bug. The API is not obvious and could be better (or the documentation), but the correct way to import a rrd from rrdtool is:

```
        RrdMemoryBackendFactory be = new RrdMemoryBackendFactory();
        RrdDb.getBuilder().setPath("imported.rrd").setExternalPath("rrdtool://path/to/file.rrd").setBackendFactory(be).doimport();
        RrdDb rrd = RrdDb.getBuilder().setPath("imported.rrd").setBackendFactory(be).build();
        rrd.getBytes();
```

**Comment by hbs** [comment] 2019-12-26 20:53
Ok for the correct way to import an RRD file, but clearly the offset parameter in the ByteBufferBackend#read method is not correctly used in the call to ByteBuffer#get

**Comment by hbs** [comment] 2019-12-26 20:55
Actually if you check the code for build and the code for import, what import does is implied in build, so no need to call doImport prior to calling build.

And this does not change the fact that using an in memory backend factory you cannot use getBytes which fails.

**Comment by fbacchella** [comment] 2019-12-26 21:07
It doesn't fails it you used .doimport() and after that .build() on a new builder, like I do in the example I gave.

**Comment by hbs** [comment] 2019-12-26 21:12
It does on the example I run.

Try calling backend.readAll() twice in a row in a ByteBufferBackend, you will see the type of failure I encounter.

**Comment by fbacchella** [comment] 2019-12-26 22:57
Closed in 8ddb829

**Closed by fbacchella** 2019-12-26 22:57 UTC

**Comment by hbs** [comment] 2019-12-26 23:36
Your fix changes the position of the buffer, I have not looked at the rest of the code base but it would probably be safer to enclose the call to position and get inside of a try { ... } finally { ... } with the finally block resetting the position to its value prior to the position/get combo call.

**Comment by fbacchella** [comment] 2019-12-27 08:35
The buffer position is never used. All operations are done from an offset.
